# Generated by Django 4.1.1 on 2022-10-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'proveedores',
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('icono', models.ImageField(upload_to='')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria')),
                ('proveedor', models.ManyToManyField(to='administracion.proveedor')),
            ],
            options={
                'verbose_name': 'productos',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
