# Generated by Django 4.1.1 on 2022-10-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'productos', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedores', 'verbose_name_plural': 'proveedores'},
        ),
    ]
