<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-10-11 01:31
=======
# Generated by Django 4.1.1 on 2022-10-07 00:24
>>>>>>> a45a3b99973779599eb19890814c3aa0526f498d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
<<<<<<< HEAD
                ('nit', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
=======
                ('nit', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'clientes',
                'verbose_name_plural': 'clientes',
            },
>>>>>>> a45a3b99973779599eb19890814c3aa0526f498d
        ),
    ]
