# Generated by Django 4.1.1 on 2022-10-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
