# Generated by Django 4.1.1 on 2022-09-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_cliente_empleado_rename_teleno_proveedor_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='disponibilidad',
            field=models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=1),
        ),
    ]
