# Generated by Django 4.1.1 on 2022-09-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_empleado_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empleado')),
                ('producto', models.ManyToManyField(to='login.producto')),
            ],
        ),
    ]
