<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-10-11 01:31
=======
# Generated by Django 4.1.1 on 2022-10-06 03:13
>>>>>>> a45a3b99973779599eb19890814c3aa0526f498d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
<<<<<<< HEAD
=======
                ('usuario', models.CharField(max_length=15)),
                ('contrasenia', models.CharField(max_length=250)),
>>>>>>> a45a3b99973779599eb19890814c3aa0526f498d
                ('tipo', models.CharField(choices=[('v', 'Vendedor'), ('a', 'Administrador')], default='v', max_length=1)),
                ('disponibilidad', models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=1)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
