# Generated by Django 4.1.1 on 2022-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('v', 'Vendedor'), ('a', 'Administrador')], default='v', max_length=1)),
                ('disponibilidad', models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=1)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuarios',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
