# Generated by Django 4.1.1 on 2022-10-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
    ]
