# Generated by Django 4.1.1 on 2022-10-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_empleado_contrasenia_remove_empleado_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'usuarios', 'verbose_name_plural': 'usuarios'},
        ),
    ]
