# Generated by Django 4.1.1 on 2022-10-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cliente',
        ),
    ]
