# Generated by Django 4.1.1 on 2022-10-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('ventas', '0005_remove_cart_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
